package main

import (
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

func main() {
	initDB()
	r := mux.NewRouter()
	r.HandleFunc("/categories", getCategories).Methods("GET")
	r.HandleFunc("/categories", createCategorie).Methods("POST")
	r.HandleFunc("/categories/{id}", getCategorie).Methods("GET")
	r.HandleFunc("/categories/{id}", updateCategorie).Methods("PUT")
	r.HandleFunc("/categories/{id}", deleteCategorie).Methods("DELETE")
	r.HandleFunc("/services", getServices).Methods("GET")
	r.HandleFunc("/services", createService).Methods("POST")
	r.HandleFunc("/services/{id}", getService).Methods("GET")
	r.HandleFunc("/services/{id}", updateService).Methods("PUT")
	r.HandleFunc("/services/{id}", deleteService).Methods("DELETE")
	r.HandleFunc("/produits", getProduits).Methods("GET")
	r.HandleFunc("/produits", createProduit).Methods("POST")
	r.HandleFunc("/produits/{id}", getProduit).Methods("GET")
	r.HandleFunc("/produits/{id}", updateProduit).Methods("PUT")
	r.HandleFunc("/produits/{id}", deleteProduit).Methods("DELETE")
	r.HandleFunc("/tarifications", getTarifications).Methods("GET")
	r.HandleFunc("/tarifications", createTarification).Methods("POST")
	r.HandleFunc("/tarifications/{id}", getTarification).Methods("GET")
	r.HandleFunc("/tarifications/{id}", updateTarification).Methods("PUT")
	r.HandleFunc("/tarifications/{id}", deleteTarification).Methods("DELETE")
	r.HandleFunc("/entreprises", getEntreprises).Methods("GET")
	r.HandleFunc("/entreprises", createEntreprise).Methods("POST")
	r.HandleFunc("/entreprises/{id}", getEntreprise).Methods("GET")
	r.HandleFunc("/entreprises/{id}", updateEntreprise).Methods("PUT")
	r.HandleFunc("/entreprises/{id}", deleteEntreprise).Methods("DELETE")
	r.HandleFunc("/utilisateurs", getUtilisateurs).Methods("GET")
	r.HandleFunc("/utilisateurs", createUtilisateur).Methods("POST")
	r.HandleFunc("/utilisateurs/{id}", getUtilisateur).Methods("GET")
	r.HandleFunc("/utilisateurs/{id}", updateUtilisateur).Methods("PUT")
	r.HandleFunc("/utilisateurs/{id}", deleteUtilisateur).Methods("DELETE")
	r.HandleFunc("/abonnements", getAbonnements).Methods("GET")
	r.HandleFunc("/abonnements", createAbonnement).Methods("POST")
	r.HandleFunc("/abonnements/{id}", getAbonnement).Methods("GET")
	r.HandleFunc("/abonnements/{id}", updateAbonnement).Methods("PUT")
	r.HandleFunc("/abonnements/{id}", deleteAbonnement).Methods("DELETE")
	r.HandleFunc("/commandes", getCommandes).Methods("GET")
	r.HandleFunc("/commandes", createCommande).Methods("POST")
	r.HandleFunc("/commandes/{id}", getCommande).Methods("GET")
	r.HandleFunc("/commandes/{id}", updateCommande).Methods("PUT")
	r.HandleFunc("/commandes/{id}", deleteCommande).Methods("DELETE")
	r.HandleFunc("/factures", getFactures).Methods("GET")
	r.HandleFunc("/factures", createFacture).Methods("POST")
	r.HandleFunc("/factures/{id}", getFacture).Methods("GET")
	r.HandleFunc("/factures/{id}", updateFacture).Methods("PUT")
	r.HandleFunc("/factures/{id}", deleteFacture).Methods("DELETE")
	r.HandleFunc("/paiements", getPaiements).Methods("GET")
	r.HandleFunc("/paiements", createPaiement).Methods("POST")
	r.HandleFunc("/paiements/{id}", getPaiement).Methods("GET")
	r.HandleFunc("/paiements/{id}", updatePaiement).Methods("PUT")
	r.HandleFunc("/paiements/{id}", deletePaiement).Methods("DELETE")
	r.HandleFunc("/tickets", getTicketSupports).Methods("GET")
	r.HandleFunc("/tickets", createTicketSupport).Methods("POST")
	r.HandleFunc("/tickets/{id}", getTicketSupport).Methods("GET")
	r.HandleFunc("/tickets/{id}", updateTicketSupport).Methods("PUT")
	r.HandleFunc("/tickets/{id}", deleteTicketSupport).Methods("DELETE")
	r.HandleFunc("/notifications", getNotifications).Methods("GET")
	r.HandleFunc("/notifications", createNotification).Methods("POST")
	r.HandleFunc("/notifications/{id}", getNotification).Methods("GET")
	r.HandleFunc("/notifications/{id}", updateNotification).Methods("PUT")
	r.HandleFunc("/notifications/{id}", deleteNotification).Methods("DELETE")
	log.Fatal(http.ListenAndServe(":8080", r))
}